[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_VONAGE_API_KEY = "aa219d99"
  VITE_VONAGE_API_SECRET = "U3Wf7s5tQqSnKQvH"
  VITE_VONAGE_SESSION_ID = "2_MX40YTIxOWQ5OX5-MTcxMDc4NjE5NzE4MH5NVnBQWjRZWFpYZzVZUEtqY0VGN1JxL0x-UH4"
  VITE_VONAGE_TOKEN = "T1==cGFydG5lcl9pZD00YTIxOWQ5OSZzaWc9ZTYxMjM0NWY2YjE4ZjI5ZDY0YzE2YzE2YzE2YzE2YzE2YzE2YzE2OnNlc3Npb25faWQ9Ml9NWDQ0WVRJeE9XUTVPWDUtTVRjeE1EYzROakU1TnpFNE1INUZOVm5CUVdqUlpXRnBZWnpWWlVFdHFZMFZHTjFKeEwweC1VSDQmY3JlYXRlX3RpbWU9MTcxMDc4NjE5NyZub25jZT0wLjEyMzQ1Njc4OSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNzEwODcyNTk3"